module.exports = [
    { name: "A.K.I." },
    { name: "Akuma" },
    { name: "Blanka" },
    { name: "Cammy" },
    { name: "Chun-Li" },
    { name: "Dee Jay" },
    { name: "Dhalsim" },
    { name: "E. Honda" },
    { name: "Ed" },
    { name: "Elena" },
    { name: "Guile" },
    { name: "Jamie" },
    { name: "JP" },
    { name: "Juri" },
    { name: "Ken" },
    { name: "Kimberly" },
    { name: "Lily" },
    { name: "Luke" },
    { name: "M. Bison" },
    { name: "Mai" },
    { name: "Manon" },
    { name: "Marisa" },
    { name: "Rashid" },
    { name: "Ryu" },
    { name: "Sagat" },
    { name: "Terry" },
    { name: "Zangief" },
    { name: "C. Viper" },
];
